version: '3.9'
services:
  app_test:
    container_name: go-api-test
    tty: true
    stdin_open: true
    restart: on-failure
    ports:
      - 8081:8080
    build:
      context: ./..
      dockerfile: Dockerfile.test
    image: go-alpine-test:1.0.0
    env_file:
      - ./../.env