version: '3'
services:
  postgresql:
    container_name: postgres
    tty: true
    stdin_open: true
    restart: on-failure
    image: postgres:12-alpine
    env_file:
      - ./db.env
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data

volumes:
  db: